
name: Auto merge development branch into master

on:
  schedule:
    - cron: '30 4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install jq
        run: sudo apt-get install jq

      # - name: Merge branch
      #   continue-on-error: true
      #   run: |
      #     merge_result=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/kapilgoel1/workflows-learn/merges -d '{"base":"main","head":"iam2","commit_message":"Shipped cool_feature!"}')
      #     echo "testing"
      #     echo $merge_result
      #     if [ -z "$merge_result" ] 
      #     then 
      #       echo "NULL";
      #     else
      #       is_merge_conflict=$(echo $merge_result | grep -c "Merge conflict")
      #       echo $is_merge_conflict
      #     fi
      #     echo "hello"
      #   id: merge-branch

      # - name: Merge branch output
      #   if: ${{ steps.merge-branch.outputs.IS_MERGE_CONFLICT > 0 }}
      #   run: |
      #     echo "The selected color is ${{ steps.merge-branch.outputs.IS_MERGE_CONFLICT }}"
      #     if [ ${{ steps.merge-branch.outputs.IS_MERGE_CONFLICT }} -gt 0 ]
      #     then
      #       echo "greater than 0"
      #     fi
        
      # - name: Run a multi-line script
      #   continue-on-error: true
      #   env:
      #     SLACK_CHANNEL: c1234
      #   run: |
      #     merge_result=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" --fail https://api.github.com/repos/kapilgoel1/workflows-learn/merges -d '{"base":"main","head":"iam2","commit_message":"Shipped cool_feature!"}' || true)
      #     echo $merge_result
      #     is_merge_conflict=$(echo $merge_result | grep -c "Merge conflict")
      #     echo "test"
      #     echo $is_merge_conflict
      #     if [ $is_merge_conflict -gt 0 ]
      #     then
      #       pr_creation_response=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/kapilgoel1/workflows-learn/pulls -d '{"title":"Merge development branch into master","body":"Please pull these awesome changes in!","head":"iam2","base":"main"}')
      #       pr_url=$(echo $pr_creation_response | jq .url)
      #       echo "PR URL IS $pr_url"
      #       if [[ "$pr_url" == null ]]
      #       then
      #         echo "Failed to create a PR. PR may already exists"
      #       else
      #         echo "slack the pr url"
      #         pr_number=$(echo $pr_creation_response | jq .number)
      #         echo $pr_number
      #         curl -X POST -F channel=$SLACK_CHANNEL -F text=" Merge conflicts between mmc-server development branch and master branch \n $pr_url" https://slack.com/api/chat.postMessage -H "Authorization: ${{ secrets.SECRET_SLACK_TOKEN }}"
      #       fi
      #     fi

      - name: Merge master into development branch. In case of merge conflicts, create PR and slack its url.
        env:
          SLACK_CHANNEL: C03FGPUT8N5
        run: |
          merge_result=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/kapilgoel1/workflows-learn/merges -d '{"base":"main","head":"iam2","commit_message":"Shipped cool_feature!"}')
          echo "test"
          if [ -z "$merge_result" ] 
          then 
            echo "NULL";
          else
            echo "line 80"
            echo $merge_result
            is_merge_conflict=$(echo $merge_result | grep -c "Merge conflict" || echo 0 && exit 1)
            echo "line 82"
            echo $is_merge_conflict
            echo "line 84"
            if [ $is_merge_conflict -gt 0 ]
            then
              echo "line87"
              pr_creation_response=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_GITHUB_TOKEN }}" https://api.github.com/repos/map-my-customers/mmc-server/pulls -d '{"title":"Merge master branch into development (Auto Generated PR)","body":"Please pull these awesome changes in!","head":"master","base":"development"}')
              pr_url=$(echo $pr_creation_response | jq .url)
              if [[ "$pr_url" == null ]]
              then
                echo "Failed to create a PR. PR may already exists"
              else
                pr_number=$(echo $pr_creation_response | jq .number)
                echo "slacking"
              fi
            fi
          fi


