# This is a basic workflow to help you get started with Actions

name: Auto merge development branch into master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          merge_result=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/kapilgoel1/workflows-learn/merges -d '{"base":"main","head":"hello","commit_message":"Shipped cool_feature!"}')
          echo $merge_result
          is_merge_conflict=$(echo $merge_result | grep -c "Merge conflict")
          echo $is_merge_conflict
          if [ $is_merge_conflict -gt 0 ]
          then
            pr_creation_response=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/kapilgoel1/workflows-learn/pulls -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"hello","base":"main"}')
            pr_url=$(echo $pr_creation_response | jq .url)
            echo pr_url
          fi

